AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 instance - Intern Task"

Parameters: 
  InstanceType: 
    Description: Select instance type
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.large
  
  
    
Resources: 
  Instance: # logical id 
    Type: AWS::EC2::Instance # type 
    Properties: 
      AvailabilityZone: us-east-1a
      InstanceType: !Ref InstanceType
      ImageId: ami-0dba2cb6798deb6d8     
      SecurityGroupIds:
        - sg-07e64362c7a9987f2
      
      Tags:
        - Key: Env 
          Value: Prod
        - Key: Name 
          Value: MyDemoEC2Instance

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'Instance'
